version: '2.1'

services:
  mymoto:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mymoto
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
